### ISSUE TITLE
cannot load web image, "image not found" error

### ISSUE THREAD

**Issue by 111qqz** [chipzoller/hugo-clarity#266]
**I have checked all the prerequisites below and I'm yet experiencing a problem**

- [y] Read the README.md
- [y] Have the extended version of Hugo installed
- [y] Used the exampleSite's config.toml as a reference
- [ ] I have included my repository link. Instead of pasting long snippets here.

**Describe the bug**

Unable to load web image, it will prompt image not found.

Here is my [blog](https://111qqz.com/2019/10/The-Programming-Language-Course/)

I think there might be something wrong with this  [code](https://github.dev/chipzoller/hugo-clarity/blob/17e6574dd5c9a87ab1033538a4b426ce9e93f18a/layouts/_default/_markup/render-image.html#L25)

if I use a web image url,  then $fileDisk doesn't exist.
![企业微信截图_16459602037280](https://user-images.githubusercontent.com/30498101/155880018-717d90a9-b1ca-4d58-b4f5-e1df268732a8.png)

**Desktop (please complete the following information):**
 - OS: win10
 - Browser chrome

**Comment by onweru** [comment]
@rootwork, could you check if there's something here? Thanks in advance.

**Comment by rootwork** [comment]
I actually just noticed this over the weekend too. I'll see what I can figure out as a fix.

**Comment by rootwork** [comment]
PR submitted. This *may* require a follow-up to address [images loaded through Hugo modules](https://github.com/rootwork/hugo-module-site) (which I found out were also broken) but I need to test that more -- and in any case this PR fixes the bug described in this issue.

**Comment by 111qqz** [comment]
Thanks for the prompt fix . I really like this theme

**Comment by rahulwagh** [comment]
I have been using theme for quite some time but when i rebased with all the latest changes, it broke my image loading and i think the above fix by @rootwork  is still not working as intended. 

I am loading the images from - `http://localhost:1313/wp-content/uploads/aws/prometheus-grafana/Prometheus-Grafana.webp` and you can see the image is available there

![image](https://user-images.githubusercontent.com/6808425/156922405-ea386023-e646-466a-9140-cf446b93ccb5.png)

But it still complains for loading the images here is the screenshot of the error - 

![image](https://user-images.githubusercontent.com/6808425/156922343-2c6aa2ac-8398-4fa7-8b87-10c5c6b6fbd8.png)

1. Are we doing anykind of image format check? because i use to load the webp image and it used to work without any problem

Let me know if you need any more details i would be happy to share, I am bit new to this setup so it will take a lot of time for me to debug the code but if you know a quick fix then it would be really great.

//Rahul

**Comment by rootwork** [comment]
@rahulwagh Initial impression is that the double-slash after `static` in the disk path is probably an issue. Do you have your static dir defined somewhere, and if so do you have a trailing slash on it? Try removing it and see if that helps.

But the hard-coded static (and for that matter content) dirs in the respective code is probably the source of this issue, and would be the source of others. I think the original reason for that kludge was that I couldn't figure out how to load the staticDir and contentDir paths in a template, but I'll spend more time tomorrow figuring out how that's done -- there must be a way.

**Comment by rahulwagh** [comment]
@rootwork  thanks for reply, looking forward for your fix. Hope it should be quick fix

**Comment by chipzoller** [comment]
This was accounted for in PR #269 . Please confirm issue is solved so this issue can be closed.

**Comment by rahulwagh** [comment]
I will rebase my branch and will confirm later during the day

**Comment by rahulwagh** [comment]
I think the issue is still there @rootwork  @chipzoller 
Today i rebased my branch and tested the new fix but it is the same problem.

Here is one screenshot for reference.

<img width="1066" alt="image" src="https://user-images.githubusercontent.com/6808425/157526220-b01c4ada-dd0f-4b43-9973-a223e0cef93c.png">

**Comment by rootwork** [comment]
@rahulwagh Can you tell us where in your directory structure your config.toml/yaml/json file is located?

**Comment by rahulwagh** [comment]
Here is my project structure, let me know if i am missing something or if you need any more details for debugging.
![image](https://user-images.githubusercontent.com/6808425/157626415-be0310fd-0217-4877-881b-96a95fda6f4e.png)

**Comment by rootwork** [comment]
Hmm, yeah it should catch that.

Can you tell me what you have defined for `staticDir`? I assume it's `wp-content/uploads/aws...` but maybe I'm assuming wrong. And is it defined in that `config.toml` file or somewhere else?

**Comment by rootwork** [comment]
And actually looking at that file structure I'm confused -- your error message says you're calling a file (`Prometheus-Grafana.webp`) in the `wp-content` subdirectory, but that doesn't appear to be a subdirectory of your project. Is it loaded through Hugo Modules perhaps? Or -- that's a WordPress directory, is it being smooshed together (technical term) with Hugo somehow?

**Comment by rahulwagh** [comment]
1. Previously i had wordpress site, later i moved from `wordpress->hugo` and kept the directory structure pretty much same to ease out the migration.
2. Here is the complete project structure of my project - I am pretty much loading every image from `/content/wp-content/uploads/......`
3. the `/static/images` directory is pretty much empty apart from some default images 
4. Let me know if it helps or i can give you the read access for troubleshooting
5. Before rebasing image loading part used to work, no matter where you are placing the image although you have to mention the correct path which in my case is `/content/wp-content/uploads/......`

![image](https://user-images.githubusercontent.com/6808425/157813860-548f9afb-6899-47ad-9a27-95ea53d05b34.png)

**Comment by rootwork** [comment]
On point 1, that should be fine, just wanted to clarify. Here are some other things that would help me narrow this down:

1. Look in your `config.toml` file, and if [`staticDir`](https://gohugo.io/content-management/static-files/) is defined anywhere, please share the path it's set to.
2. The screenshot you have of the image that's not loading (`Prometheus-Grafana.webp`) -- it looks like that's set as a featured image for the blog post. Is that right? If so can you share the line from that post where the featured image is set, so I can see how you are referencing the path to that image?
3. Does the same thing happen if you try to include the image in the body of the post (using the Markdown `![alt](path/to/image "caption")`? If so can you also share that line so I can see how the path is being referenced?

I think this might just be a mismatch between what `staticDir` is set to and how the files are being referenced. It may be confusing but essentially you're treating `content/wp-content/uploads` as your static dir -- that's probably fine but because it's a child of your `contentDir` (`content`) it's possible something strange is going on. But since it worked before I think maybe it's just a setting that the image renderer isn't picking up somehow. Anyway, if you can share the above that would help me narrow it down.

**Comment by rahulwagh** [comment]
1. I haven't defined `staticDir` inside my `config.toml` 
2. Yes the image is set as featured image. Here is example of front matter. Both feature as well as thumbnail are not loading
```
---
title: Prometheus-Grafana Vs Zabbix
author: Rahul Wagh
type: post
date: 2022-02-18
excerpt: This blog post focus on the key differences between Prometheus-Grafana versus Zabbix
url: /prometheous-grafana-vs-zabbix/
featured_image: /wp-content/uploads/aws/prometheus-grafana/Prometheus-Grafana.webp
categories: Prometheus-Grafana
featured: false
thumbnail: /wp-content/uploads/aws/prometheus-grafana/Prometheus-Grafana.webp
draft : false
---
```

3. I tried the `![alt](path/to/image "caption")` but it did not work 
4. Here is `config.toml` probably you could find the missing config entry ?
```
# set `baseurl` to your root domain
# if you set it to "/" share icon won't work properly on production
baseurl = "https://jhooq.com"  # Include trailing slash
title = "Jhooq"
author = "Rahul Wagh"
copyright = "Copyright © 2019–2020, Jhooq; all rights reserved."
# canonifyurls = true
paginate = 10
theme = "jhooq-theme"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = "--"
    lineNoStart = 1
    lineNos = true # always set to true # else line numbers won't show at all! even when you toggle them on in the UI
    lineNumbersInTable = false # toggling this on (i.e to true) or deleting this line will break the code blocks functionality. Will
    noClasses = false
    # style = "monokai"
    tabWidth = 2
  [markup.goldmark.renderer]
    hardWraps = false
    unsafe = true # change to true to enable inclusion of rawHTML and math functions
    xhtml = false

[params]
author = "Rahul Wagh"
twitter = "@wagh_rahul"
largeTwitterCard = false # set to true if you want to show a large twitter card image. The default is a small twitter card image
introDescription = "Its all about Open Source and DevOps, here I talk about Kubernetes, Docker, Java, Spring boot and practices."
# description = "" # set your site's description here. will be use for home page content meta tags (seo). Alternatively set this description in your homepage content file i.e content/_index.md. Whatever is set in the latter will take precedence

# Google analytics Id
ga_analytics = "UA-xxxxxxxxx"

# limit the number of taxonomies links shown on the sidebar of each page by default.
numberOfTagsShown = 14 # Applies for all other default & custom taxonomies. e.g categories, brands see https://gohugo.io/content-management/taxonomies#what-is-a-taxonomy

# will be used on share >> twitter, facebook, linkedin
fallBackOgImage = "images/thumbnail.png" 

# sets the maximum number of lines per codeblock. The codeblock will however be scrollable and expandable.
codeMaxLines = 50

# disable showing line numbers by default. Switch to `true` if you'd rather have them on.
codeLineNumbers = false


# directory(s) where your articles are located
mainSections = ["post"] # see config details here https://gohugo.io/functions/where/#mainsections

# center logo on navbar
centerLogo = false # Set to "true" for centering or "false" for left aligned.

logo = "logos/logo.png"

# Label Non inline images on an article body
figurePositionShow = false # toggle on or off globally
# you can toggle this behaviour on or off on per page using the same variable inside your articles frontmatter
figurePositionLabel = "Figure" # the text before image number e.g Figure 1.0

# Set the collapsed mobile navigation to either appear from the left or the right
mobileNavigation = "left" # if you prefer right change to 'right'

[permalinks]
  post = "/:title"

```

**Comment by rootwork** [comment]
OK, so here's what's going on -- if you just want the solution, skip to the bottom. But explanation first.

By [default](https://gohugo.io/content-management/static-files/), Hugo establishes its static directory as the path `static/`, a subdirectory of your Hugo project. If you tell it in a Markdown page/post to load the file `apple.png`, Hugo goes to look for it in `static/apple.png`. (Unless you're using Page Bundles, which you're not.)

So when you ask Hugo to load the file `/wp-content/uploads/aws/prometheus-grafana/Prometheus-Grafana.webp` it's looking at the path `static/wp-content/uploads/aws/prometheus-grafana/Prometheus-Grafana.webp` for the file. It doesn't find the file there, so you get the image error.

The reason this was working *before* is because Hugo does two things after it looks for the file: First, when it finds the file, it moves it into your rendered site directory (by default `public/`) and, second, it constructs the web path to the file for the generated HTML page(s). Surprisingly, not finding a file doesn't prevent Hugo from taking this last step. So Hugo would look for your file in the local file system and fail to find it, but then it would still go ahead and render a page with the image's `src` set to `https://yourdomain.tld/wp-content/uploads/aws/prometheus-grafana/Prometheus-Grafana.webp` which -- on the web -- *was* a valid path, so it would work. I suspect Hugo was actually outputting some errors in the console when it failed to find the file, and that if you had looked for things like image width and height tags (which Hugo inserts when it processes the image file on the disk) they would have been missing.

Now we are putting that second step Hugo takes behind a gate: We're telling Hugo to check if the file exists on the local disk, and if it doesn't exist then to render the error, full stop. Hugo never gets to that second step of creating the image `src`. One could make the argument (and I'm open to doing a new pull request to do this if it's wanted) that we should go back to the old way of not blocking that step -- we wouldn't be able to do things like automatically inserting the width and height or generating other image formats (and again, I suspect Hugo would complain in the console) but if the web path was still valid then the image would still load. In my opinion what we're doing now is more clearly surfacing an error that previously was going unnoticed, which I think is better -- but I could be convinced otherwise.

### Solutions for you:

You have a few options:

1. In your `config.toml`, add a line that sets your static directory, like `staticDir = content/wp-content/uploads/aws` (I'm assuming here all your images are in the `aws` directory, but if they're all in the `prometheus-grafana` directory you could append that as well.) As I said above, I don't know if Hugo will complain that your static directory is a child of your content directory, but if it accepts it OK then I think this is the best solution. You'll then have to update all of the references to images in your content to strip out `/wp-content/uploads/aws/`, which you should be able to do pretty quickly with find and replace tools.
2. You could instead simply treat all of your images as external (web-only) images, and provide a full web path to them, e.g. `https://yourdomain.tld/wp-content/uploads/aws/prometheus-grafana/Prometheus-Grafana.webp`. In that case you would lose the extra image formats because Hugo would no longer have access to actually processing those images.
3. You could move the `wp-content` directory from `content` to `static`. This wouldn't require you to change anything in the content, but since I don't know what else you might be referencing from this directory or how, it could break other things on your site.
4. You *might* be able to set your static directory as a relative path, e.g. `staticDir = ../content/wp-content/uploads/aws` -- this would be like the first option but wouldn't require you to change anything in the content files. But I suspect Hugo doesn't allow you to traverse up the directory tree for security reasons, so I kind of doubt this would work.

Let me know which of those you try and if it works!

**Comment by rahulwagh** [comment]
Thanks @rootwork I really appreciate your detailed answer. 

Finally it worked and i am able to load the images. So what i did is moved my `wp-content` directory inside the `static` directory and it started to load all the images. 
![image](https://user-images.githubusercontent.com/6808425/158536122-8a4136b9-a405-4739-8b1a-795cd9c24272.png)


Although making and entry(`staticDir = content/wp-content/uploads/aws`) in `config.toml` did not work for me.

What is the long term strategy or preferred way of placing an image - "Should i always put my images under `static` directory?"

**Comment by thedaxshepherd** [comment]
First I hope this is the proper place to post this. I did not feel like opening a new issue was the right thing to do.
When I followed the instructions to test the theme using Option 2 once I ran "hugo server --themesDir ../.." I got the error message: 
![image](https://user-images.githubusercontent.com/60486315/158879458-982766af-b6b1-4420-8045-cb74c6e037f1.png)
After trying to track down the problem I realized it was the two sample posts (markdown-syntax.md and markdown-syntax.pt.md) that were the issue. Either removing those files or the reference "![Jane Doe](https://raw.githubusercontent.com/chipzoller/hugo-clarity/master/static/images/jane-doe.png "This is Jane Doe")". 
This is not impacting my site but was something that I ran into when trying out the theme and I didn't want this to stop others from being able to test and eventually use the theme.

**Comment by rootwork** [comment]
Hmm, OK, that looks like it's a Windows path thing; for some reason it's not recognizing the external-ness of the URL to the image and trying to concatenate it with the static path (see in the error message `...\static\https:\...` (and yes, it's rewriting that URL protocol to only have one slash too!)

I don't have a Windows machine to easily test on but I'll see if I can figure out what's causing that.

**Comment by rootwork** [comment]
Hey @onweru @chipzoller I'm thinking maybe I should just do a PR to remove the image error message. That is the source of all of this headache -- checking whether the file exists "on disk" in order to render the error message. I haven't been able to figure out the above Windows thing, and I also think there's a continuing issue if you load the theme using Hugo modules. I also still feel unsure about the hacky way I had to load the `staticDir` and `contentDir` variables from a site's config.

By default Hugo will build sites with references to broken images, and as we've uncovered sometimes what seems on build like broken images are in fact not broken once the site is live. Maybe we should just respect that, remove the efforts to generate a visible error message and consequently reduce complexity around all of this. There are, after all, other tools one could use to check for broken images on a site (whether built by Hugo or not).

What do you think?

**Comment by onweru** [comment]
> as we've uncovered sometimes what seems on build like broken images are in fact not broken once the site is live

@rootwork, I'm concur

**Comment by chipzoller** [comment]
That'd be fine, although it was a nice addition.
